In [265]:
import pandas as pd
from pandas import DataFrame
import numpy as np

In [266]:
import csv
def ReadFile (filename):
    f = open (filename)
    r = csv.reader (f)
    mentions = dict()
    for line in r:
        student = line[0]
        discipline = line[6]
        type_d = line[7]
        sem_rate = int(line[8])
        bonus = int(line[9])
        exam_rate = int(line[10])
        rate = 0
        if type_d == 'exam':
            if (sem_rate >= 38) & (exam_rate >= 22):
                rate = sem_rate + exam_rate + bonus
        else: 
            if (sem_rate >= 60):
                rate = sem_rate + bonus
        if not student in mentions:
            mentions[student] = dict()
        mentions[student][discipline] = rate
    f.close()
    return mentions

In [267]:
students_test = ReadFile("raw_data32.csv")
df = DataFrame(students_test)
df.columns.name = 'studentID'
df.index.name = 'discipline'
df

studentID      1     2     3     4     5      6      7     8     9
discipline
1002         NaN   0.0  60.0   NaN   NaN    NaN    NaN  60.0   NaN
1009        60.0   NaN   NaN  60.0  67.0   82.0   67.0   NaN  78.0
1025         NaN   0.0   0.0   NaN   NaN    NaN    NaN  60.0   NaN
1054        65.0   NaN   NaN  65.0  81.0   79.0   81.0   NaN  94.0
1058         0.0   NaN   NaN   0.0   0.0    0.0    0.0   NaN   0.0
11           0.0   0.0   0.0   0.0  98.0   98.0  100.0   0.0  76.0
1117         NaN   0.0  61.0   NaN   NaN    NaN    NaN  62.0   NaN
1136         NaN   0.0   0.0   NaN   NaN    NaN    NaN   0.0   NaN
1154         0.0   NaN   NaN   0.0   0.0    0.0    0.0   NaN   0.0
1176        60.0   NaN   NaN  75.0  82.0   79.0   76.0   NaN  78.0
1200        60.0   NaN   NaN   0.0  89.0  100.0  102.0   NaN  90.0
1203         NaN   0.0   0.0   NaN   NaN    NaN    NaN   0.0   NaN
1204         0.0   NaN   NaN  61.0  72.0   72.0   91.0   NaN  60.0
1233        72.0   NaN   NaN  66.0  71.0   87.0   71.0   NaN  76.0
1253        63.0   NaN   NaN  61.0  71.0   89.0   78.0   NaN  64.0
1300         NaN   0.0   0.0   NaN   NaN    NaN    NaN   0.0   NaN
1401         NaN   NaN  62.0   NaN   NaN    NaN    NaN  60.0   NaN
1438         NaN   NaN  84.0   NaN   NaN    NaN    NaN  69.0   NaN
1475        60.0   NaN   NaN   0.0  60.0   63.0   65.0   NaN  62.0
1486        60.0   NaN   NaN   0.0  71.0   77.0   71.0   NaN  82.0
1491         NaN   NaN  60.0   NaN   NaN    NaN    NaN  60.0   NaN
1506        60.0   NaN   NaN   0.0  60.0   74.0   60.0   NaN  67.0
1514        60.0   NaN   NaN   0.0   0.0   92.0   60.0   NaN  60.0
1527         NaN   NaN  60.0   NaN   NaN    NaN    NaN  60.0   NaN
1544         NaN   NaN  60.0   NaN   NaN    NaN    NaN  60.0   NaN
163         63.0   0.0   0.0   0.0  88.0   85.0   81.0   0.0  74.0
1631        70.0   NaN   NaN   0.0  85.0   85.0   70.0   NaN  60.0
1651        63.0   NaN   NaN   0.0  71.0   77.0   71.0   NaN  79.0
1685         NaN   NaN  60.0   NaN   NaN    NaN    NaN  87.0   NaN
1686        60.0   NaN   NaN   0.0  71.0   74.0   92.0   NaN  63.0
...          ...   ...   ...   ...   ...    ...    ...   ...   ...
2235        60.0   NaN   NaN   0.0   NaN    NaN    NaN   NaN   NaN
2245         NaN   NaN   NaN   NaN   0.0    0.0    0.0   NaN   0.0
2256         NaN   NaN   NaN   NaN   NaN    NaN    NaN   0.0   NaN
2322         NaN   NaN   NaN   NaN   0.0    0.0    0.0   NaN   0.0
2326         NaN   NaN   NaN   NaN   NaN    NaN    NaN   0.0   NaN
2341         NaN   NaN   NaN   NaN   0.0    0.0    0.0   NaN   0.0
2346         0.0   NaN   NaN   0.0   0.0    0.0    0.0   NaN   0.0
2350         NaN   NaN   NaN   NaN   NaN    NaN    NaN   0.0   NaN
2365         0.0   NaN   NaN   0.0   NaN    NaN    NaN   NaN   NaN
2366         0.0   NaN   NaN   0.0   NaN    NaN    NaN   NaN   NaN
2369         NaN   NaN   NaN   0.0   NaN    NaN    NaN   0.0   NaN
2373         NaN   NaN   NaN   NaN   0.0    0.0    0.0   NaN   0.0
2388         0.0   NaN   NaN   0.0   NaN    NaN    NaN   NaN   NaN
31          77.0  60.0  63.0   0.0  85.0   96.0   89.0   0.0  71.0
424         60.0   0.0   0.0  63.0  91.0  102.0  100.0   0.0  94.0
49           0.0   0.0   0.0  60.0  72.0   85.0   71.0   0.0   0.0
491         61.0   0.0   0.0  68.0  84.0   80.0   86.0   0.0  67.0
52          61.0   0.0   0.0  60.0  71.0   85.0   73.0   0.0  61.0
524          0.0   NaN   NaN   NaN   NaN    NaN    NaN   NaN   NaN
53          60.0   NaN   NaN   NaN   NaN    NaN    NaN   NaN   NaN
569         60.0   0.0   0.0  60.0  79.0   71.0   68.0   0.0  68.0
579         61.0   0.0   0.0  65.0  71.0   85.0   74.0   0.0  62.0
64           NaN   NaN   NaN   NaN   NaN   90.0   87.0   NaN  73.0
65           0.0   0.0   0.0   0.0   0.0    0.0    0.0   0.0   0.0
668          0.0   0.0   0.0  60.0   0.0    0.0    0.0   0.0   0.0
694         60.0   0.0   0.0  60.0  60.0   73.0   75.0   0.0  63.0
700         60.0   0.0   0.0  60.0  70.0  100.0   86.0   0.0  76.0
802          0.0   0.0   0.0   0.0  62.0    0.0    0.0   0.0   0.0
889          NaN   0.0   0.0   NaN   NaN    NaN    NaN   0.0   NaN
974          NaN   0.0  60.0   NaN   NaN    NaN    NaN  60.0   NaN

[94 rows x 9 columns]

In [268]:
# Рассчитаем матрицу схожести студентов, используя коэффициент Пирсона
corr = df.corr().stack() # находим корреляции
corr.index.names = ['studentID','corr_studentID']
corr = corr.reset_index()
corr.rename(columns={0:'corr'},inplace=True)
corr = corr[(corr['studentID'] != corr['corr_studentID']) # уберем корреляцию с самим собой
           &(corr['corr']>0)] # уберем корреляции, равные нулю и отрицательные
corr

   studentID corr_studentID      corr
1          1              2  0.337149
2          1              3  0.337149
3          1              4  0.236960
4          1              5  0.536385
5          1              6  0.731118
6          1              7  0.687869
7          1              9  0.795454
8          2              1  0.337149
10         2              3  0.481342
12         2              5  0.176366
13         2              6  0.206145
14         2              7  0.194284
16         2              9  0.168763
17         3              1  0.337149
18         3              2  0.481342
21         3              5  0.176366
22         3              6  0.206145
23         3              7  0.194284
24         3              8  0.759954
25         3              9  0.168763
26         4              1  0.236960
30         4              5  0.282538
31         4              6  0.349127
32         4              7  0.342016
33         4              9  0.268427
34         5              1  0.536385
35         5              2  0.176366
36         5              3  0.176366
37         5              4  0.282538
39         5              6  0.771757
40         5              7  0.868897
41         5              9  0.723641
42         6              1  0.731118
43         6              2  0.206145
44         6              3  0.206145
45         6              4  0.349127
46         6              5  0.771757
48         6              7  0.923326
49         6              9  0.772677
50         7              1  0.687869
51         7              2  0.194284
52         7              3  0.194284
53         7              4  0.342016
54         7              5  0.868897
55         7              6  0.923326
57         7              9  0.823316
59         8              3  0.759954
61         9              1  0.795454
62         9              2  0.168763
63         9              3  0.168763
64         9              4  0.268427
65         9              5  0.723641
66         9              6  0.772677
67         9              7  0.823316

In [269]:
df1 = df.stack().reset_index()
df1.rename(columns={0:'rating'},inplace=True)
df1

    discipline studentID  rating
0         1002         2     0.0
1         1002         3    60.0
2         1002         8    60.0
3         1009         1    60.0
4         1009         4    60.0
5         1009         5    67.0
6         1009         6    82.0
7         1009         7    67.0
8         1009         9    78.0
9         1025         2     0.0
10        1025         3     0.0
11        1025         8    60.0
12        1054         1    65.0
13        1054         4    65.0
14        1054         5    81.0
15        1054         6    79.0
16        1054         7    81.0
17        1054         9    94.0
18        1058         1     0.0
19        1058         4     0.0
20        1058         5     0.0
21        1058         6     0.0
22        1058         7     0.0
23        1058         9     0.0
24          11         1     0.0
25          11         2     0.0
26          11         3     0.0
27          11         4     0.0
28          11         5    98.0
29          11         6    98.0
..         ...       ...     ...
368        694         4    60.0
369        694         5    60.0
370        694         6    73.0
371        694         7    75.0
372        694         8     0.0
373        694         9    63.0
374        700         1    60.0
375        700         2     0.0
376        700         3     0.0
377        700         4    60.0
378        700         5    70.0
379        700         6   100.0
380        700         7    86.0
381        700         8     0.0
382        700         9    76.0
383        802         1     0.0
384        802         2     0.0
385        802         3     0.0
386        802         4     0.0
387        802         5    62.0
388        802         6     0.0
389        802         7     0.0
390        802         8     0.0
391        802         9     0.0
392        889         2     0.0
393        889         3     0.0
394        889         8     0.0
395        974         2     0.0
396        974         3    60.0
397        974         8    60.0

[398 rows x 3 columns]

In [274]:
# соединение таблиц корреляции и оценок по дисциплинам (left join in DB)
# keys: corr_studentID in table corr and studentId in table df1
# rating второго студента (С кем коррелируем)
ratings_and_corrs = pd.merge(corr,df1,
                    left_on='corr_studentID', right_on='studentID',
                    how='left')
ratings_and_corrs.drop(['studentID_y'],axis=1,inplace=True)
ratings_and_corrs

     studentID_x corr_studentID      corr discipline  rating
0              1              2  0.337149       1002     0.0
1              1              2  0.337149       1025     0.0
2              1              2  0.337149         11     0.0
3              1              2  0.337149       1117     0.0
4              1              2  0.337149       1136     0.0
5              1              2  0.337149       1203     0.0
6              1              2  0.337149       1300     0.0
7              1              2  0.337149        163     0.0
8              1              2  0.337149         31    60.0
9              1              2  0.337149        424     0.0
10             1              2  0.337149         49     0.0
11             1              2  0.337149        491     0.0
12             1              2  0.337149         52     0.0
13             1              2  0.337149        569     0.0
14             1              2  0.337149        579     0.0
15             1              2  0.337149         65     0.0
16             1              2  0.337149        668     0.0
17             1              2  0.337149        694     0.0
18             1              2  0.337149        700     0.0
19             1              2  0.337149        802     0.0
20             1              2  0.337149        889     0.0
21             1              2  0.337149        974     0.0
22             1              3  0.337149       1002    60.0
23             1              3  0.337149       1025     0.0
24             1              3  0.337149         11     0.0
25             1              3  0.337149       1117    61.0
26             1              3  0.337149       1136     0.0
27             1              3  0.337149       1203     0.0
28             1              3  0.337149       1300     0.0
29             1              3  0.337149       1401    62.0
...          ...            ...       ...        ...     ...
2394           9              7  0.823316       1824    60.0
2395           9              7  0.823316       1870     0.0
2396           9              7  0.823316       1892    68.0
2397           9              7  0.823316       1897    65.0
2398           9              7  0.823316       1918    60.0
2399           9              7  0.823316       1981    86.0
2400           9              7  0.823316       2014    68.0
2401           9              7  0.823316       2033    73.0
2402           9              7  0.823316       2075     0.0
2403           9              7  0.823316       2103    61.0
2404           9              7  0.823316       2137     0.0
2405           9              7  0.823316       2156    61.0
2406           9              7  0.823316       2245     0.0
2407           9              7  0.823316       2322     0.0
2408           9              7  0.823316       2341     0.0
2409           9              7  0.823316       2346     0.0
2410           9              7  0.823316       2373     0.0
2411           9              7  0.823316         31    89.0
2412           9              7  0.823316        424   100.0
2413           9              7  0.823316         49    71.0
2414           9              7  0.823316        491    86.0
2415           9              7  0.823316         52    73.0
2416           9              7  0.823316        569    68.0
2417           9              7  0.823316        579    74.0
2418           9              7  0.823316         64    87.0
2419           9              7  0.823316         65     0.0
2420           9              7  0.823316        668     0.0
2421           9              7  0.823316        694    75.0
2422           9              7  0.823316        700    86.0
2423           9              7  0.823316        802     0.0

[2424 rows x 5 columns]

In [286]:
# Чтобы получить прогноз оценок определенного студента нужно взвесить оценки всех студентов на их корреляцию 
# с определенным студентом
# Рассчитаем прогнозные оценки для всех студентов сразу.
def weighted(df):
    prediction = (df['corr']*df['rating']).sum() / df['corr'].sum()
    return pd.Series([prediction], index=['pred'])

predictions = ratings_and_corrs.groupby(['studentID_x','discipline']).apply(weighted)
#predictions['pred']
# predictions.unstack() # предположительные баллы

studentID_x  discipline
1            1002          30.000000
             1009          73.043954
             1025           0.000000
             1054          82.702700
             1058           0.000000
             11            69.211067
             1117          30.500000
             1136           0.000000
             1154           0.000000
             1176          78.264423
             1200          87.892362
             1203           0.000000
             1204          72.307087
             1233          75.849864
             1253          74.359488
             1300           0.000000
             1401          62.000000
             1438          84.000000
             1475          57.659139
             1486          69.765822
             1491          60.000000
             1506          60.530905
             1514          52.300341
             1527          60.000000
             1544          60.000000
             163           61.147677
             1631          68.149403
             1651          68.967117
             1685          60.000000
             1686          68.808016
                             ...
9            2156          44.317259
             2166           0.000000
             2197           0.000000
             2235          44.861440
             2245           0.000000
             2322           0.000000
             2341           0.000000
             2346           0.000000
             2365           0.000000
             2366           0.000000
             2369           0.000000
             2373           0.000000
             2388           0.000000
             31            78.195705
             424           78.374354
             49            51.690055
             491           69.921550
             52            64.978184
             524            0.000000
             53            60.000000
             569           62.306783
             579           65.560131
             64            88.452408
             65             0.000000
             668            4.328257
             694           60.575919
             700           70.561077
             802           12.057313
             889            0.000000
             974           30.000000
Name: pred, dtype: float64

In [272]:
# не нужно учитывать курсы, которые студент уже прошел
mask = df.T.isnull().stack()
#predictions[mask.values]

In [273]:
df.T #реальные баллы

discipline,1002,1009,1025,1054,1058,11,1117,1136,1154,1176,...,569,579,64,65,668,694,700,802,889,974
studentID,,,,,,,,,,,,,,,,,,,,,
1,NaN,60.0,NaN,65.0,0.0,0.0,NaN,NaN,0.0,60.0,...,60.0,61.0,NaN,0.0,0.0,60.0,60.0,0.0,NaN,NaN
2,0.0,NaN,0.0,NaN,NaN,0.0,0.0,0.0,NaN,NaN,...,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,60.0,NaN,0.0,NaN,NaN,0.0,61.0,0.0,NaN,NaN,...,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,60.0
4,NaN,60.0,NaN,65.0,0.0,0.0,NaN,NaN,0.0,75.0,...,60.0,65.0,NaN,0.0,60.0,60.0,60.0,0.0,NaN,NaN
5,NaN,67.0,NaN,81.0,0.0,98.0,NaN,NaN,0.0,82.0,...,79.0,71.0,NaN,0.0,0.0,60.0,70.0,62.0,NaN,NaN
6,NaN,82.0,NaN,79.0,0.0,98.0,NaN,NaN,0.0,79.0,...,71.0,85.0,90.0,0.0,0.0,73.0,100.0,0.0,NaN,NaN
7,NaN,67.0,NaN,81.0,0.0,100.0,NaN,NaN,0.0,76.0,...,68.0,74.0,87.0,0.0,0.0,75.0,86.0,0.0,NaN,NaN
8,60.0,NaN,60.0,NaN,NaN,0.0,62.0,0.0,NaN,NaN,...,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,60.0
9,NaN,78.0,NaN,94.0,0.0,76.0,NaN,NaN,0.0,78.0,...,68.0,62.0,73.0,0.0,0.0,63.0,76.0,0.0,NaN,NaN